# Generated by Django 5.1.1 on 2024-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyclops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyes',
            name='name',
        ),
        migrations.AlterField(
            model_name='eyes',
            name='videofile',
            field=models.FileField(upload_to='./'),
        ),
    ]
