# Generated by Django 5.1.5 on 2025-03-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyclops', '0002_remove_eyes_name_alter_eyes_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.FileField(upload_to='processed_videos/')),
                ('graph_file', models.FileField(upload_to='processed_graphs/')),
                ('frame_diameter', models.JSONField()),
                ('smoothed_diameter_spline', models.JSONField()),
                ('maxPD', models.FloatField(blank=True, null=True)),
                ('minPD', models.FloatField(blank=True, null=True)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('max_constriction', models.FloatField(blank=True, null=True)),
                ('mcv', models.FloatField(blank=True, null=True)),
                ('_75PerOfMaxPD', models.FloatField(blank=True, null=True)),
                ('mdv', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
