# Generated by Django 5.1.5 on 2025-03-20 23:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyclops', '0003_plrresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='plrresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plrresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
