# Generated by Django 5.1.5 on 2025-03-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cyclops', '0004_plrresult_updated_at_alter_plrresult_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plrresult',
            old_name='mcv',
            new_name='acv',
        ),
        migrations.RenameField(
            model_name='plrresult',
            old_name='mdv',
            new_name='adv',
        ),
    ]
