# Generated by Django 5.1.5 on 2025-04-12 18:24

import Cyclops.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyclops', '0005_rename_mcv_plrresult_acv_rename_mdv_plrresult_adv'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_file', models.FileField(upload_to=Cyclops.models.test_video_upload_path)),
                ('plotData', models.JSONField()),
                ('fps', models.FloatField(blank=True, null=True)),
                ('maxPD', models.FloatField(blank=True, null=True)),
                ('minPD', models.FloatField(blank=True, null=True)),
                ('latency', models.CharField(blank=True, max_length=10, null=True)),
                ('max_constriction', models.FloatField(blank=True, null=True)),
                ('seventyFivePercentRecovery', models.CharField(blank=True, max_length=10, null=True)),
                ('adv', models.FloatField(blank=True, null=True)),
                ('acv', models.FloatField(blank=True, null=True)),
                ('iris_bounding_boxes', models.JSONField(blank=True, null=True)),
                ('pupil_bounding_boxes', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
